AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dataset-deployment for covid19-aomori

Parameters:
  ProductId:
    Type: String
  Env:
    Type: String

Resources:
  TriggerCircleciPipeline:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProductId}-${Env}-trigger-circleci-pipeline
      Runtime: python3.8
      CodeUri: function/
      Handler: cicleci.call_pipeline
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TZ: Asia/Tokyo
          ProductId: !Ref ProductId
          Env: !Ref Env
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: '*'
      Events:
        ObjectCreated:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt CircleciPipelineQueue.Arn
            BatchSize: 1
      Tags:
        ProductId: !Ref ProductId
        Env: !Ref Env

  DataSetStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProductId}-${Env}-dataset-store
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Topic: !Ref ObjectCreatedEventWatcher
    DependsOn:
      - ObjectCreatedEventWatcherPolicy

  DataSetStoreBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataSetStore
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${DataSetStore}/*"
            Principal: '*'

  ObjectCreatedEventWatcher:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProductId}-${Env}-object-created-event-watcher

  ObjectCreatedEventWatcherPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ObjectCreatedEventWatcher
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sns:Publish
            Resource:
              - !Ref ObjectCreatedEventWatcher
            Principal:
              AWS: '*'
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::${ProductId}-${Env}-dataset-store
    DependsOn:
      - ObjectCreatedEventWatcher

  ObjectCreatedEventWatcherSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt CircleciPipelineQueue.Arn
      TopicArn: !Ref ObjectCreatedEventWatcher

  CircleciPipelineQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ProductId}-${Env}-circleci-pipeline-queue
      VisibilityTimeout: 30

  CircleciPipelineQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref CircleciPipelineQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt CircleciPipelineQueue.Arn
            Principal:
              AWS: '*'
            Condition:
              ArnLike:
                aws:SourceArn: !Ref ObjectCreatedEventWatcher
